### ISSUE TITLE
Чому люди проводять менше часу, спілкуючись з людьми, а більше з телефонами?

### ISSUE THREAD

**Issue by Julia1910** [Julia1910/hello-world#3]
Які у вас думки щодо цього?

**Comment by Aryan-soul** [comment]
Можливо через те, що погляди усіх друзів навіть зараз там

**Comment by Aryan-soul** [comment]
Навіть зараз

**Comment by Julia1910** [comment]
І як зробити так, щоб "живе" спілкування збільшувалося?
