### ISSUE TITLE
Купити квитки

### ISSUE THREAD

**Issue by Julia1910** [Julia1910/hello-world#4]
Яким шляхом будемо добиратися?

**Comment by Julia1910** [comment]
Є варіанти автобусом або потягом

**Comment by Aryan-soul** [comment]
Думаю потягом буде значно комфортніше і дешевше

**Comment by Julia1910** [comment]
Добре. Беремо потягом.

**Comment by Julia1910** [comment]
Є квитки на 26.04 на 22:17 зі Львову до Одеси. Прибуття 27.04 о 12:10. Підходить?

**Comment by Aryan-soul** [comment]
Так, вони є у наявності і усім підходить.

**Comment by Aryan-soul** [comment]
Вже купив

**Comment by Julia1910** [comment]
Додай їх у вигляді файлів.
