### ISSUE TITLE
У мене є два спальні мішки. Хто візьме?

### ISSUE THREAD

**Issue by Aryan-soul** [Julia1910/hello-world#5]
Один з них літній, а інший зимовий. Кому весь час холодно під час сну - пишіть.

**Comment by Julia1910** [comment]
Мені завжди холодно, можна мені зимовий?)

**Comment by Aryan-soul** [comment]
А що мені за це буде?

**Comment by Julia1910** [comment]
Можливо шоколадка
Якщо я не замерзну:)

**Comment by Aryan-soul** [comment]
Ну добре, готуй шоколадку

**Comment by Aryan-soul** [comment]
Несу до тебе

**Comment by Julia1910** [comment]
Супер)
